# Generated by Django 4.2.6 on 2023-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rough_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='desc',
            field=models.TextField(default=False),
        ),
    ]
